In [1]:
import os
import sys
import pandas as pd
import pickle
import string  
import numpy as np
#from sas7bdat import SAS7BDAT

pd.options.display.max_rows = 999

# infra_aplic_filtro

In [2]:
# Reading the SAS Transport file
df_infra = pd.read_sas('infra_aplic_filtro.sas7bdat',format = 'sas7bdat', encoding='latin-1')

In [3]:
# Display the first few rows of the dataframe
df_infra.head(1).transpose()

                                                                                  0
ArquivoXML                        C:\Users\r1698984\Documents\svn\importxml\trat...
ID_CNPQ_INFRAESTRUTURA                                             0004889261552055
NRO_ID_INFRAESTRUTURA                                                        3608.0
TXT_NOME_INFRAESTRUTURA                                   Laboratório de Amostragem
NOME_DA_INSTITUICAO_VINCULO                  SENAI - Departamento Regional da Bahia
INSTITUICAO_CORRIGIDA                                                         SENAI
SIGLA                                                                           AMT
NOME_DA_CLASSIFICACAO                                                   Laboratório
ANO_DE_INICIO_DA_OPERACAO                                                      2002
VALOR_DA_AREA_FISICA_PD                                                          60
TIPO_DE_MEDIDA_DA_AREA_FISICA_PD                                                 m2
UF                                                                               BA
COD_MUNICIPIO_IBGE                                                          2919207
LATITUDE                                                                -12.8859252
LONGITUDE                                                        -38.29789870000002
LOCALIDADE                                                         Lauro de Freitas
ESTADO                                                                        BAHIA
COOP_EMPR_BRA                                                                   NaN
COOP_EMPR_EXT                                                                   NaN
COOP_INST_BRA                                                                   NaN
COOP_INST_EXT                                                                   NaN
COOP_AGEN_BRA                                                                   NaN
COOP_AGEN_EXT                                                                   NaN
COOP_AGEN_GOV                                                                   NaN
SEM_COOPERACAO                                                                    1
POSSUI_ACREDITACAO                                                              1.0
MOD_ENSAIO                                                                      1.0
MOD_CALIBRACAO                                                                  0.0
DEMAIS_MODALIDADES                                                              0.0
ORGAO_ACRED_INMETRO                                                             1.0
ORGAO_ACRED_OUTRO                                                               0.0
NUM_DOUTOR_APOIO                                                                0.0
NUM_MESTRE_APOIO                                                                0.0
NUM_ESPECIAL_APOIO                                                              0.0
NUM_GRADUADO_APOIO                                                              0.0
NUM_NIVEL_MEDIO_APOIO                                                           0.0
NUM_SERVIDOR_FUNC                                                               0.0
NUM_PREST_SERV_TERC                                                             0.0
NUM_VINC_OUTRO                                                                  0.0
ESTUD_DOUT                                                                      0.0
ESTUD_ESP                                                                       0.0
ESTUD_GRAD                                                                      0.0
ESTUD_MEST                                                                      0.0
USU_PESQ_MESMA_INST                                                             0.0
USU_PESQ_OUTRAS_INST                                                            0.0
USU_ALUNO_POS                                                                   0.0
USU_ALUNO_GRAD                                                                  0.0
USU_PESQ_EMPRESAS                                                               0.0
SEM_DEMANDA_USUEXT                                                              NaN
USU_PESQ_BRASILEIROS                                                            0.0
USU_PESQ_ESTRANGEIROS                                                           0.0
ACESSOPOL_VINCULO                                                               0.0
ACESSOPOL_FORMULARIO                                                            0.0
ACESSOPOL_AVAL_VIABILIDADE                                                      0.0
ACESSOPOL_FINSDIDATICOS                                                         0.0
ACESSOPOL_MEDIANTE_REMUN                                                        0.0
SEM_POL_FORMAL_ACESSO                                                           1.0
ACESSOPOL_ACORDO                                                                0.0
ACESSOPOL_SOLICIT_PREVIA                                                        0.0
ACESSOPOL_PARCERIA                                                              0.0
ACESSOPOL_AVAL_COMISSAO                                                         0.0
ACESSOPOL_DISP_USU_EXTERNOS                                                     0.0
ACESSOPOL_OUTRO                                                                 0.0
AGEN_PREVIO                                                                     0.0
TERMO_RESP_CONF                                                                 0.0
USU_EXEC_ENSAIO_E_EQUIP                                                         0.0
TREIN_ANTES_UTILI                                                               0.0
USU_EXEC_SUPERV                                                                 0.0
EQUIPE_EXECUTA                                                                  0.0
ENSAIO_ACOMP_REMOTA_USU                                                         0.0
RESUL_DISP_POST                                                                 0.0
USU_FORN_INSUMOS                                                                0.0
OUTRO_PROCED                                                                    0.0
NAO_EXIS_PROC_FORMAIS                                                           0.0
PRESTA_SERV_TEC                                                                 1.0
PRESTA_SERV_EMPR                                                                1.0
ESTIMA_VALOR_LABINFRA                                                Até R$ 500 mil
ESTIMA_VALOR_EQUIPPESQ                           Acima de R$ 100 mil até R$ 250 mil
ESTIMA_VALOR_CUSTOP                                                   Até R$ 50 mil
ESTIMA_VALOR_RECEITA                                                  Até R$ 50 mil
IMPACT_DESP_ENERGIA                                                             4.0
IMPACT_DESP_INSUMOS                                                             3.0
IMPACT_DESP_MANUTEN                                                             4.0
IMPACT_DESP_PESSOAL                                                             5.0
IMPACT_DESP_OUTRO                                                               NaN
FONTERENDA_Petrobras                                                            0.0
FONTERENDA_PREST_SERVICOS                                                       0.0
FONTERENDA_OUTRA_INST_PUB                                                       0.0
FONTERENDA_PROPRIA_INST                                                         0.0
FONTERENDA_CNPq                                                                 0.0
FONTERENDA_Capes                                                                0.0
FONTERENDA_Finep                                                                0.0
FONTERENDA_FUND_ESTAD_AMPARO                                                    0.0
FONTERENDA_OUTRA                                                                0.0
FONTERENDA_EMPREPRIVADA                                                         0.0
FONTERENDA_OUTRA_EMPPUBLCA                                                      0.0
TIPO_CAPACIDADE_TECNICA           Adequada e compatível com a observada em outra...
CONDICAOOP_INSTALFISICAS                                                        Bom
CONDICAOOP_EQUIPAMENTOS                                                         Bom
CONDICAOOP_MANUTENCAO                                                           Bom
CONDICAOOP_INSUMOS_PESQUISA                                                     Bom
AVALRH_NRO_PESQUISADORES                                                   Adequado
AVALRH_FORMACAO_PESQUISADORES                                              Adequado
AVALRH_NROPROFISSIONAIS_APOIO                                              Adequado
AVALRH_QUALIFICA_PROFISSIONAIS                                             Adequado
PERIODO_MODERNIZACAO                                                      Até 1 ano
ATIV_ENSINO                                                              Esporádico
ATIV_PESQ                                                                Esporádico
ATIV_TECNO                                                    Alguns dias da semana
ATIV_EXT_TECNO                                                Alguns dias da semana
ATIV_SERV_TECNO                                                            Contínuo
ATIV_OUTRA                                                                      NaN

In [7]:
# Display the first few rows of the dataframe
df_infra.shape

(1760, 112)

In [8]:
nomes_laboratorios = df_infra.TXT_NOME_INFRAESTRUTURA.unique()
#nomes_coordenadores nomes_pesquisadores nomes_laboratorios

In [9]:
df_infra.dtypes

ArquivoXML                           object
ID_CNPQ_INFRAESTRUTURA               object
NRO_ID_INFRAESTRUTURA               float64
TXT_NOME_INFRAESTRUTURA              object
NOME_DA_INSTITUICAO_VINCULO          object
INSTITUICAO_CORRIGIDA                object
SIGLA                                object
NOME_DA_CLASSIFICACAO                object
ANO_DE_INICIO_DA_OPERACAO            object
VALOR_DA_AREA_FISICA_PD              object
TIPO_DE_MEDIDA_DA_AREA_FISICA_PD     object
UF                                   object
COD_MUNICIPIO_IBGE                   object
LATITUDE                             object
LONGITUDE                            object
LOCALIDADE                           object
ESTADO                               object
COOP_EMPR_BRA                        object
COOP_EMPR_EXT                        object
COOP_INST_BRA                        object
COOP_INST_EXT                        object
COOP_AGEN_BRA                        object
COOP_AGEN_EXT                        object
COOP_AGEN_GOV                        object
SEM_COOPERACAO                       object
POSSUI_ACREDITACAO                  float64
MOD_ENSAIO                          float64
MOD_CALIBRACAO                      float64
DEMAIS_MODALIDADES                  float64
ORGAO_ACRED_INMETRO                 float64
ORGAO_ACRED_OUTRO                   float64
NUM_DOUTOR_APOIO                    float64
NUM_MESTRE_APOIO                    float64
NUM_ESPECIAL_APOIO                  float64
NUM_GRADUADO_APOIO                  float64
NUM_NIVEL_MEDIO_APOIO               float64
NUM_SERVIDOR_FUNC                   float64
NUM_PREST_SERV_TERC                 float64
NUM_VINC_OUTRO                      float64
ESTUD_DOUT                          float64
ESTUD_ESP                           float64
ESTUD_GRAD                          float64
ESTUD_MEST                          float64
USU_PESQ_MESMA_INST                 float64
USU_PESQ_OUTRAS_INST                float64
USU_ALUNO_POS                       float64
USU_ALUNO_GRAD                      float64
USU_PESQ_EMPRESAS                   float64
SEM_DEMANDA_USUEXT                  float64
USU_PESQ_BRASILEIROS                float64
USU_PESQ_ESTRANGEIROS               float64
ACESSOPOL_VINCULO                   float64
ACESSOPOL_FORMULARIO                float64
ACESSOPOL_AVAL_VIABILIDADE          float64
ACESSOPOL_FINSDIDATICOS             float64
ACESSOPOL_MEDIANTE_REMUN            float64
SEM_POL_FORMAL_ACESSO               float64
ACESSOPOL_ACORDO                    float64
ACESSOPOL_SOLICIT_PREVIA            float64
ACESSOPOL_PARCERIA                  float64
ACESSOPOL_AVAL_COMISSAO             float64
ACESSOPOL_DISP_USU_EXTERNOS         float64
ACESSOPOL_OUTRO                     float64
AGEN_PREVIO                         float64
TERMO_RESP_CONF                     float64
USU_EXEC_ENSAIO_E_EQUIP             float64
TREIN_ANTES_UTILI                   float64
USU_EXEC_SUPERV                     float64
EQUIPE_EXECUTA                      float64
ENSAIO_ACOMP_REMOTA_USU             float64
RESUL_DISP_POST                     float64
USU_FORN_INSUMOS                    float64
OUTRO_PROCED                        float64
NAO_EXIS_PROC_FORMAIS               float64
PRESTA_SERV_TEC                     float64
PRESTA_SERV_EMPR                    float64
ESTIMA_VALOR_LABINFRA                object
ESTIMA_VALOR_EQUIPPESQ               object
ESTIMA_VALOR_CUSTOP                  object
ESTIMA_VALOR_RECEITA                 object
IMPACT_DESP_ENERGIA                 float64
IMPACT_DESP_INSUMOS                 float64
IMPACT_DESP_MANUTEN                 float64
IMPACT_DESP_PESSOAL                 float64
IMPACT_DESP_OUTRO                   float64
FONTERENDA_Petrobras                float64
FONTERENDA_PREST_SERVICOS           float64
FONTERENDA_OUTRA_INST_PUB           float64
FONTERENDA_PROPRIA_INST             float64
FONTERENDA_CNPq                     float64
FONTERENDA_Capes                    float64
FONTERENDA_Finep                    float64
FONTERENDA_FUND_ESTAD_AMPARO        float64
FONTERENDA_OUTRA                    float64
FONTERENDA_EMPREPRIVADA             float64
FONTERENDA_OUTRA_EMPPUBLCA          float64
TIPO_CAPACIDADE_TECNICA              object
CONDICAOOP_INSTALFISICAS             object
CONDICAOOP_EQUIPAMENTOS              object
CONDICAOOP_MANUTENCAO                object
CONDICAOOP_INSUMOS_PESQUISA          object
AVALRH_NRO_PESQUISADORES             object
AVALRH_FORMACAO_PESQUISADORES        object
AVALRH_NROPROFISSIONAIS_APOIO        object
AVALRH_QUALIFICA_PROFISSIONAIS       object
PERIODO_MODERNIZACAO                 object
ATIV_ENSINO                          object
ATIV_PESQ                            object
ATIV_TECNO                           object
ATIV_EXT_TECNO                       object
ATIV_SERV_TECNO                      object
ATIV_OUTRA                           object
dtype: object

# Pesquisadores da Infraestrutura: Livro Petro

In [ ]:
# Reading the SAS Transport file
df_pesq = pd.read_sas('re_pesquisador_infraestrutura.sas7bdat', format='sas7bdat', encoding='latin-1')

In [11]:
df_pesq.shape

(8473, 11)

In [12]:
df_pesq.head(1).transpose()

                                                0
ID_CNPQ_INFRAESTRUTURA           5551401962126380
NRO_ID_INFRAESTRUTURA                        1903
NOME_COMPLETO           Rodrigo Alvarenga Rezende
NRO_ID_CNPQ                      9334199887874167
CPF                                   01038081670
TITULACAO_MAXIMA                        Doutorado
PAIS_DE_NASCIMENTO                         Brasil
DATA_DE_NASCIMENTO                       29031975
TIPO_DE_VINCULO                          Bolsista
TEMPO_DE_DEDICACAO           Mais de 30h semanais
NRO_ID_INFRA_FILTRADA                         1.0

In [16]:
df_pesq.dtypes

ID_CNPQ_INFRAESTRUTURA     object
NRO_ID_INFRAESTRUTURA      object
NOME_COMPLETO              object
NRO_ID_CNPQ                object
CPF                        object
TITULACAO_MAXIMA           object
PAIS_DE_NASCIMENTO         object
DATA_DE_NASCIMENTO         object
TIPO_DE_VINCULO            object
TEMPO_DE_DEDICACAO         object
NRO_ID_INFRA_FILTRADA     float64
dtype: object

In [17]:
nomes_pesquisadores = df_pesq.NOME_COMPLETO.unique()
#nomes_coordenadores nomes_pesquisadores

In [18]:
# Display the first few rows of the dataframe
df_infra.shape

(1760, 112)

# Setor de Aplicacão da Infraestrutura: Livro Petro

In [22]:
# Reading the SAS Transport file
df_setor = pd.read_sas('setor_aplicacao.sas7bdat',format = 'sas7bdat', encoding='latin-1')

In [23]:
df_setor.head()

,ID_CNPQ_INFRAESTRUTURA,NRO_ID_INFRAESTRUTURA,CODIGO_CNAE,CODIGO_SECAO,NOME_SECAO,CODIGO_GRUPO,NOME_GRUPO,H,I,J
0,0004889261552055,3608,C.10.3,420030,Indústrias de Transformação,420034,"Fabricação de conservas de frutas, legumes e o...",NaN,NaN,NaN
1,0004889261552055,3608,C.20.9,420030,Indústrias de Transformação,",420084",Fabricação de produtos e preparados químicos d...,NaN,NaN,NaN
2,0004889261552055,3608,C.21.2,420030,Indústrias de Transformação,",420086",Fabricação de produtos farmacêuticos,NaN,NaN,NaN
3,0012810424938613,2151,P.85.9,420325,Educação,420330,Outras atividades de ensino,NaN,NaN,NaN
4,0012810424938613,2151,P.85.2,420325,Educação,",420390",Ensino médio,NaN,NaN,NaN

In [24]:
# Display the first few rows of the dataframe
df_setor.shape

(5436, 10)

# Coordenadores Livro Petro

In [25]:
# Reading the SAS Transport file
df_coordenador = pd.read_sas('vi_coordenador.sas7bdat',format = 'sas7bdat', encoding='latin-1')

In [26]:
df_coordenador.shape

(3125, 10)

In [27]:
df_coordenador.head()

,ID_CNPQ_INFRAESTRUTURA,NRO_ID_INFRAESTRUTURA,NOME_COMPLETO,NRO_ID_CNPQ,CPF,TITULACAO_MAXIMA,PAIS_DE_NASCIMENTO,H,I,J
0,0004889261552055,3608,Jicarla Portela Rebouças,6457786446393543,89958802520,Mestrado,Brasil,NaN,NaN,NaN
1,0012810424938613,2151,Eduardo Barrere,0735298552666402,16284057830,Doutorado,Brasil,NaN,NaN,NaN
2,0012810424938613,2151,Marcelo Ferreira Moreno,6352224173110416,02834644616,Doutorado,Brasil,NaN,NaN,NaN
3,0029150548901446,4579,Antonio Carlos Caetano de Souza,1468507187090017,28728756894,Mestrado,Brasil,NaN,NaN,NaN
4,0029150548901446,4579,Eduardo Manfredini Ferreira,0078492970206109,13843698805,Doutorado,Brasil,NaN,NaN,NaN

In [28]:
df_coordenador.dtypes

ID_CNPQ_INFRAESTRUTURA    object
NRO_ID_INFRAESTRUTURA     object
NOME_COMPLETO             object
NRO_ID_CNPQ               object
CPF                       object
TITULACAO_MAXIMA          object
PAIS_DE_NASCIMENTO        object
H                         object
I                         object
J                         object
dtype: object

In [29]:
nomes_coordenadores = df_coordenador.NOME_COMPLETO.unique()

In [28]:
# Estudar esse site
# https://huyenchip.com/2024/07/25/genai-platform.html

# Realizar um cruzamento entre os dados: 
- i) Pesquisadores da lista dos 250 MCTI seleção PNIPE 
- ii) Pesquisadores que responderam ao questionário do livro da petrobras (2023). 
- iii) Verificaremos a hipótese de baixa sobreposição entre as tabelas.
    - a) Se a sobreposição foi baixa, ha um problema. 

OBS: A baixa sobreposição é o efeito de "aprisionamento" dos cientistas em determinadas linhas de financiamento:
    - Pesquisadores financiados pelo MCTI tender a permanescer assim, sem receber recursos do P&D da Petrobras.
    - Pesquisadores financiados pelo P&D da Petrobras, tendem a não utilizar recursos do MCTI.

# Laboratório do MCTI

In [30]:
#Importando o conjunto de dados
df_equip = pd.read_excel('C:/Users/patrick.franco/Documents/GitHub/enchentes/webscraping/labs_mcti2.xlsx' , sheet_name='codigos_equip')

In [31]:
df_equip.dtypes

site_mcti    object
lab           int64
codigos      object
dtype: object

In [32]:
df_equip.head()

                                    site_mcti    lab       codigos
0  https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod29G3ZW/22
1  https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod0XA11S/22
2  https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod44ZD3D/22
3  https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod3KV65S/22
4  https://pnipe.mcti.gov.br/laboratory/10008  10008  Cod7G4LW0/22

In [36]:
#df_coordenador.head()

In [ ]:
#df_nomes_petro.to_excel('labs_mcti_petro1.xlsx',sheet_name='cadatro_nomes')
#df_areas_petro.to_excel('labs_mcti_petro2.xlsx',sheet_name='areas_labs')
#df_equip_petro.to_excel('labs_mcti_petro3.xlsx',sheet_name='codigos_equip')

In [33]:
#Importando o conjunto de dados
df_nomes = pd.read_excel('C:/Users/patrick.franco/Documents/GitHub/enchentes/webscraping/labs_mcti2.xlsx' , sheet_name='cadatro_nomes')

In [34]:
df_nomes.shape

(6323, 13)

In [35]:
df_nomes.head()

,lab,site_mcti,nome_lab,data_de_criacao,universidade,nome_responsavel,tel,endereco,cidade,cep,email,site_lab,sobre
0,10006,https://pnipe.mcti.gov.br/laboratory/10006,CTO - Centro de Tecnologias Ômicas,17/03/2022,USP - Universidade de São Paulo,Mario Hiroyuki Hirata,(55) 11998-3877,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,NaN,NaN,Utilizado para o desenvolvimento de pesquisas ...
1,10008,https://pnipe.mcti.gov.br/laboratory/10008,NB3 - Laboratório Multiusuário com Nivel de Bi...,17/03/2022,USP - Universidade de São Paulo,Mario Hiroyuki Hirata,(55) 11998-3877,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,mhhirata@usp.br,https://uspmulti.prp.usp.br/public/centrais/126,O laboratório de biossegurança Nível 3 do Depa...
2,10037,https://pnipe.mcti.gov.br/laboratory/10037,IA BMF - ICB/USP - Instalação Animal do Depart...,18/03/2022,USP - Universidade de São Paulo,Eliana Akamine,(11) 3091-7317,Professor Lineu Prestes,São Paulo - SP - 1524,Veja como chegar,biot.farmaco@icb.usp.br,NaN,Trata-se de biotério utilizado pelos pesquisad...
3,1004,https://pnipe.mcti.gov.br/laboratory/1004,Mietto Lab - Lab. de Biologia Celular,22/09/2020,UFJF - Universidade Federal de Juiz de Fora,Bruno Siqueira Mietto,(21) 99934-0074,Rua José Lourenço Kelmer,Juiz de Fora - MG - s/n,Veja como chegar,bruno.mietto@ufjf.edu.br,NaN,Laboratório de pesquisa em neurobiologia com ê...
4,10057,https://pnipe.mcti.gov.br/laboratory/10057,QA/SECTEC/LAPOC - Laboratório de Radiometria e...,21/03/2022,CNEN - Comissão Nacional de Energia Nuclear,Rodrigo Leandro Bonifácio,(35) 3716-7029,Poços de Caldas - Andradas,Poços de Caldas - MG - km13,Veja como chegar,lapoc@cnen.gov.br,http://www.cnenpc.gov.br,Os laboratórios de Química Analítica e Radiome...

In [36]:
#codigos_equip
df_equip_petro = df_nomes[ (df_nomes['nome_responsavel'].isin(nomes_coordenadores)) |
                           (df_nomes['nome_responsavel'].isin(nomes_pesquisadores)) |
                           (df_nomes['nome_lab'].isin(nomes_laboratorios)) ].copy()

In [ ]:
#nomes_coordenadores nomes_pesquisadores nomes_laboratorios

In [37]:
df_equip_petro.shape

(360, 13)

In [40]:
#Importando o conjunto de dados
df_nomes_petro = pd.read_excel('C:/Users/patrick.franco/Documents/GitHub/enchentes/webscraping/labs_mcti_petro.xlsx' , sheet_name='cadatro_nomes')

In [41]:
df_nomes_petro.head()

,lab,site_mcti,nome_lab,data_de_criacao,universidade,nome_responsavel,tel,endereco,cidade,cep,email,site_lab,sobre
0,10117,https://pnipe.mcti.gov.br/laboratory/10117,LATAB - Laboratório de Tabaco e Derivados,28/03/2022,INT - Instituto Nacional de Tecnologia,SIMONE CHIAPETTA,(21) 2123-1090,Av. Venezuela,Rio de Janeiro - RJ - 82,Veja como chegar,NaN,NaN,Laboratório que atua na prestação de serviços ...
1,104,https://pnipe.mcti.gov.br/laboratory/104,LabMAM - Laboratório de Estudos Marinhos e Amb...,09/09/2020,PUC-RIO - Pontifícia Universidade Católica do ...,Renato da Silva Carreira,(21) 98890-9515,Rua Marquês de São Vicente 225,Rio de Janeiro - RJ - 225,Veja como chegar,carreira@puc-rio.br,www.qui.puc-rio.br,Laboratório especializado na determinação de a...
2,11025,https://pnipe.mcti.gov.br/laboratory/11025,Geo_Model - Laboratório de Modelagem Física em...,24/05/2022,UENF - Universidade Estadual do Norte Fluminen...,Fernando Saboya Albuquerque Junior.,(22) 2739-7382,Alberto Lamego,Campos dos Goytacazes - RJ - 2000,Veja como chegar,NaN,NaN,"Instalada na UENF, entrou em operação em 2009...."
3,11302,https://pnipe.mcti.gov.br/laboratory/11302,LEGG - Laboratório de Engenharia Geotécnica e ...,30/06/2022,UFRGS - Universidade Federal do Rio Grande do Sul,Lucas Festugato,(51) 3308-4740,Osvaldo Aranha,Porto Alegre - RS - 99,Veja como chegar,NaN,NaN,Por contar com equipamentos avançados para o e...
4,1148,https://pnipe.mcti.gov.br/laboratory/1148,LABRMN-L - Laboratório Multiusuário de Ressonâ...,24/09/2020,UFRJ - Universidade Federal do Rio de Janeiro,Carlos Kaiser,(21) 98762-6970,Avenida Athos da Silveira Ramos 149,Rio de Janeiro - RJ - 148,Veja como chegar,labrmn@iq.ufrj.br,https://labrmn.iq.ufrj.br/,Laboratório de análises instrumentais por RMN ...

In [42]:
#codigos_equip
df_equip_petro2 = df_nomes_petro[ (df_nomes_petro['nome_responsavel'].isin(nomes_coordenadores)) |
                                  (df_nomes_petro['nome_responsavel'].isin(nomes_pesquisadores)) |
                                  (df_nomes_petro['nome_lab'].isin(nomes_laboratorios)) ].copy()

In [43]:
df_equip_petro2.shape

(26, 13)