In [1]:
import os
import sys
import pandas as pd
import pickle

In [2]:
#Importando o conjunto de dados
patrim = pd.read_csv(filepath_or_buffer = 'patrimonio-uniao.csv', sep=',', decimal='.')

In [3]:
patrim.head()

,orgao_superior_codigo_siorg,orgao_superior_nome,orgao_superior_sigla,orgao_codigo_siorg,orgao_nome,orgao_sigla,orgao_como_no_raiox_nome,orgao_como_no_raiox_sigla,ano_mes_referencia,regime_utilizacao,tipo_destinacao,tipo_imovel,endereco,municipio_nome,municipio_cod_ibge,uf,metro_quadrado_area,metro_quadrado_construida,valor_imovel,valor_aluguel
0,26,PRESIDÊNCIA DA REPÚBLICA,PR,26,PRESIDÊNCIA DA REPÚBLICA,PR,PRESIDÊNCIA DA REPÚBLICA,PR,202405,CESSÃO - OUTROS,Palácio,Palácio,PAL SAI/SUL LOTE 'B' S/N PALACIO DO JABURU,BRASÍLIA,5300108,DF,203798.00,3559.93,2933860.69,0.0
1,26,PRESIDÊNCIA DA REPÚBLICA,PR,26,PRESIDÊNCIA DA REPÚBLICA,PR,PRESIDÊNCIA DA REPÚBLICA,PR,202405,ENTREGA - ADMINISTRAÇÃO FEDERAL DIRETA,Açude,Espelho D'Água,A - s/n Represa do Estreito,SACRAMENTO,3156908,MG,5624913.08,NaN,16593493.58,0.0
2,26,PRESIDÊNCIA DA REPÚBLICA,PR,26,PRESIDÊNCIA DA REPÚBLICA,PR,PRESIDÊNCIA DA REPÚBLICA,PR,202405,ENTREGA - ADMINISTRAÇÃO FEDERAL DIRETA,Edifício / Prédio,Edifício / Prédio,"AL COUTO MAGALHAES 277 Antiga Rua S-07, fundos...",GOIÂNIA,5208707,GO,3055.00,757.38,8847564.64,0.0
3,26,PRESIDÊNCIA DA REPÚBLICA,PR,26,PRESIDÊNCIA DA REPÚBLICA,PR,PRESIDÊNCIA DA REPÚBLICA,PR,202405,ENTREGA - ADMINISTRAÇÃO FEDERAL DIRETA,Edifício / Prédio,Edifício / Prédio,AV HERMES DA FONSECA 1076,NATAL,2408102,RN,679.00,679.00,1727134.61,0.0
4,26,PRESIDÊNCIA DA REPÚBLICA,PR,26,PRESIDÊNCIA DA REPÚBLICA,PR,PRESIDÊNCIA DA REPÚBLICA,PR,202405,ENTREGA - ADMINISTRAÇÃO FEDERAL DIRETA,Edifício / Prédio,Edifício / Prédio,AV IRACEMA CARVAO NUNES 625,MACAPÁ,1600303,AP,1920.00,496.00,6731710.80,0.0

In [4]:
patrim.dtypes

orgao_superior_codigo_siorg      int64
orgao_superior_nome             object
orgao_superior_sigla            object
orgao_codigo_siorg               int64
orgao_nome                      object
orgao_sigla                     object
orgao_como_no_raiox_nome        object
orgao_como_no_raiox_sigla       object
ano_mes_referencia               int64
regime_utilizacao               object
tipo_destinacao                 object
tipo_imovel                     object
endereco                        object
municipio_nome                  object
municipio_cod_ibge               int64
uf                              object
metro_quadrado_area            float64
metro_quadrado_construida      float64
valor_imovel                   float64
valor_aluguel                  float64
dtype: object

In [5]:
#na coluna "tipo de destinação" da pra selecionar "equipamento/instalação" , "laboratório", "reserva" e "universidade"

In [6]:
#https://zenodo.org/records/11185049

In [7]:
patrim[['tipo_destinacao','orgao_superior_codigo_siorg']].groupby('tipo_destinacao').count().to_excel('tipo_destinacap.xlsx')

In [8]:
labs = patrim[(patrim['tipo_destinacao']=='Laboratório')|(patrim['tipo_imovel']=='Laboratório')].copy()

In [9]:
#labs[['orgao_superior_nome','orgao_superior_codigo_siorg']].groupby('orgao_superior_nome').count()

In [10]:
#labs[['regime_utilizacao','orgao_superior_codigo_siorg']].groupby('regime_utilizacao').count()

In [11]:
#labs[['tipo_imovel','orgao_superior_codigo_siorg']].groupby('tipo_imovel').count()

In [ ]:
labs.head()

In [13]:
labs.shape

(105, 20)

## Dados da Fapesp

## Unificando Dados da FAPESP

In [14]:
#Importando o conjunto de dados
fapesp = []

for sheeto in ['auxilios_em_andamento','auxilios_concluidos','bolsas_exterior_em_andamento','bolsas_exterior_concluidas','bolsas_no_brasil_em_andamento','bolsas_no_brasil_concluidas']:
    df = pd.read_excel('C:/Users/patrick.franco/Documents/GitHub/enchentes/fapesp/fapesp.xlsx',
                        sheet_name= sheeto , 
                        dtype = {'Supervisor':'str' , 'Local de Pesquisa':'str'}
                        )
    df['origem'] = sheeto
    fapesp.append(df)


#auxilios_em_andamento
#auxilios_concluidos
#bolsas_exterior_em_andamento
#bolsas_exterior_concluidas
#bolsas_no_brasil_em_andamento
#bolsas_no_brasil_concluidas

In [15]:
fapesp[0].head()

,N. Processo,Título (Português),Título (Inglês),Beneficiário,Instituição,Cidade Instituição,Instituição Parceira,Empresa,Município,Pesquisador Responsável,...,Data de Início,Data de Término,Acordo(s)/Convênio(s) de Cooperação com a FAPESP,Instituições no Exterior,Pais de Origem,Pesquisador responsável no exterior,Resumo (Português),Resumo (Inglês),Processos Vinculados,origem
0,24/19386-0,"Doenças associadas ao HPV: rastreamento, vacin...","HPV associated diseases: screening, prophylact...",Laura Cristina Sichero Vettorazzo,Secretaria da Saúde (São Paulo - Estado). Coor...,São Paulo,NaN,NaN,NaN,Laura Cristina Sichero Vettorazzo,...,2025-09-11,2025-09-13,NaN,NaN,NaN,NaN,The event will benefit basic and clinical rese...,NaN,NaN,auxilios_em_andamento
1,24/19194-4,Simpósio Satélite Estudos de coorte de interes...,Satellite Symposium Lifecycle cohort studies,Marly Augusto Cardoso,Universidade de São Paulo (USP). Faculdade de ...,São Paulo,NaN,NaN,NaN,Marly Augusto Cardoso,...,2025-09-04,2025-09-05,NaN,NaN,NaN,NaN,Apresentamos aqui proposta para organização de...,NaN,NaN,auxilios_em_andamento
2,24/06872-4,Escola São Paulo de Ciência Avançada sobre Pol...,São Paulo School of Advanced Science on Emergi...,Geórgia Christina Labuto Araújo,Universidade Federal de São Paulo (UNIFESP). C...,Diadema,NaN,NaN,NaN,Geórgia Christina Labuto Araújo,...,2025-09-02,2025-09-13,NaN,NaN,NaN,NaN,Estudos recentes indicam o rompimento de seis ...,NaN,NaN,auxilios_em_andamento
3,24/09315-9,"ERGONOMIA, USABILIDADE E OS DESAFIOS CONTEMPO...","ERGONOMICS, USABILITY, AND CONTEMPORÂNEOS CHAL...",Luis Carlos Paschoarelli,Universidade Estadual Paulista (UNESP). Campus...,Bauru,NaN,NaN,NaN,Luis Carlos Paschoarelli,...,2025-08-25,2026-08-24,NaN,Centro De Ciências Exatas E Tecnologia/Ccet/Ufma,Brasil,NaN,"Desde 2002, o Laboratório de Ergonomia e Inter...","Since 2002, the Ergonomics and Interfaces Labo...",NaN,auxilios_em_andamento
4,24/06867-0,Escola São Paulo de Ciência Avançada em Mudanç...,São Paulo School of Advanced Science in System...,Sérgio Giovanetti Lazzarini,Instituto de Ensino e Pesquisa (Insper),São Paulo,NaN,NaN,NaN,Sérgio Giovanetti Lazzarini,...,2025-08-18,2025-08-27,NaN,NaN,NaN,NaN,"Sustentabilidade, visa atender às necessidades...",NaN,NaN,auxilios_em_andamento

In [16]:
import numpy as np
import pandas as pd

df_fapesp = pd.concat(fapesp).reset_index()
df_fapesp.replace([np.inf, -np.inf, np.nan], 0,inplace=True)

In [17]:
df_fapesp.dtypes

index                                                int64
N. Processo                                         object
Título (Português)                                  object
Título (Inglês)                                     object
Beneficiário                                        object
Instituição                                         object
Cidade Instituição                                  object
Instituição Parceira                                object
Empresa                                             object
Município                                           object
Pesquisador Responsável                             object
Pesquisadores Principais                            object
Pesquisadores Associados                            object
Supervisor                                           int64
Local de Pesquisa                                   object
Pesquisador Visitante                               object
Instituição do Pesquisador Visitante                object
Modalidade de apoio                                 object
Grande Área do Conhecimento                         object
Área do Conhecimento                                object
Subárea do Conhecimento                             object
Assuntos                                            object
Data de Início                                      object
Data de Término                                     object
Acordo(s)/Convênio(s) de Cooperação com a FAPESP    object
Instituições no Exterior                            object
Pais de Origem                                      object
Pesquisador responsável no exterior                 object
Resumo (Português)                                  object
Resumo (Inglês)                                     object
Processos Vinculados                                object
origem                                              object
dtype: object

In [18]:
import string  
import pandas as pd

df_fapesp['LAB_RESUMO0']   = np.where(df_fapesp['Resumo (Português)'].str.contains("laboratório", case=False, na=False), 1,0)
df_fapesp['LAB_RESUMO1']   = np.where(df_fapesp['Título (Português)'].str.contains("laboratório", case=False, na=False), 1,0)
df_fapesp['LAB_RESUMO2']   = np.where(df_fapesp['Assuntos'].str.contains("laboratório", case=False, na=False), 1,0)


df_fapesp['CENTRO_CEPID'] = np.where(df_fapesp['Modalidade de apoio'].str.contains("Centros de Pesquisa, Inovação e Difusão", case=False, na=False), 1,0)
df_fapesp['CENTRO_CPE']   = np.where(df_fapesp['Modalidade de apoio'].str.contains("Centros de Pesquisa em Engenharia", case=False, na=False), 1,0)
df_fapesp['CENTRO_PIPE']  = np.where(df_fapesp['Modalidade de apoio'].str.contains("Pesquisa Inovativa em Pequenas Empresas", case=False, na=False), 1,0)
df_fapesp['CENTRO_PITE']  = np.where(df_fapesp['Modalidade de apoio'].str.contains("Pesquisa em Parceria para Inovação Tecnológica", case=False, na=False), 1,0)
df_fapesp['CENTRO_PAPI']  = np.where(df_fapesp['Modalidade de apoio'].str.contains("Apoio à Propriedade Intelectual (PAPI/NUPLITEC)", case=False, na=False), 1,0)

C:\Users\patrick.franco\AppData\Local\Temp\ipykernel_4076\2776715958.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_fapesp['CENTRO_PAPI']  = np.where(df_fapesp['Modalidade de apoio'].str.contains("Apoio à Propriedade Intelectual (PAPI/NUPLITEC)", case=False, na=False), 1,0)

In [19]:
df_fapesp['LAB_RESUMO'] = np.where( ( (df_fapesp['LAB_RESUMO0']==1) | (df_fapesp['LAB_RESUMO1']==1) | (df_fapesp['LAB_RESUMO2']==1) ), 1,0)

In [20]:
print( "\n Laboratórios identificados através do Resumo (fapesp): "   ,df_fapesp[['LAB_RESUMO0','LAB_RESUMO1','LAB_RESUMO2']][df_fapesp['LAB_RESUMO0']==1].shape[0],
       "\n Laboratórios identificados através do Título (fapesp): "   ,df_fapesp[['LAB_RESUMO0','LAB_RESUMO1','LAB_RESUMO2']][df_fapesp['LAB_RESUMO1']==1].shape[0],
       "\n Laboratórios identificados através do assunto (fapesp): "  ,df_fapesp[['LAB_RESUMO0','LAB_RESUMO1','LAB_RESUMO2']][df_fapesp['LAB_RESUMO2']==1].shape[0],
       "\n Total de Laboratórios (campos: Resumo, Assunto, Título): " ,df_fapesp[['LAB_RESUMO','LAB_RESUMO1','LAB_RESUMO2']][df_fapesp['LAB_RESUMO']==1].shape[0] )

 Laboratórios identificados através do Resumo (fapesp):  21819
 Laboratórios identificados através do Título (fapesp):  2479
 Laboratórios identificados através do assunto (fapesp):  2225
 Total de Laboratórios (campos: Resumo, Assunto, Título):  22759

In [21]:
df_fapesp[['LAB_RESUMO','CENTRO_CEPID','CENTRO_CPE','CENTRO_PIPE','CENTRO_PITE','CENTRO_PAPI','Resumo (Português)']][df_fapesp['LAB_RESUMO']==1].head()

,LAB_RESUMO,CENTRO_CEPID,CENTRO_CPE,CENTRO_PIPE,CENTRO_PITE,CENTRO_PAPI,Resumo (Português)
3,1,0,0,0,0,0,"Desde 2002, o Laboratório de Ergonomia e Inter..."
8,1,0,0,0,0,0,"Com base na Linguística Interacional (IL), na ..."
11,1,0,0,0,0,0,A professora Mercedes Maroto-Valer estará envo...
12,1,0,0,0,0,0,O Prof. John M. Andresen estará envolvida na c...
20,1,0,0,0,0,0,A internacionalização da pesquisa no estado de...

In [22]:
df_fapesp[['LAB_RESUMO','Empresa','Área do Conhecimento']].groupby('LAB_RESUMO').count()

            Empresa  Área do Conhecimento
LAB_RESUMO
0            270117                270117
1             22759                 22759

In [24]:
#df_fapesp[['LAB_RESUMO','Laboratorio8','Laboratorio9','Laboratorio10']][~df_fapesp['Laboratorio9'].isnull()].tail()

In [25]:
df_fapesp['Laboratorio0']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?\))", expand=False)
df_fapesp['Laboratorio1']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?\.)", expand=False)
df_fapesp['Laboratorio2']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?\,)", expand=False)
df_fapesp['Laboratorio3']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?\-)", expand=False)
df_fapesp['Laboratorio4']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?\\)", expand=False)
df_fapesp['Laboratorio5']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?no campus)", expand=False)
df_fapesp['Laboratorio6']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?Faculdade)", expand=False)
df_fapesp['Laboratorio7']  = df_fapesp['Resumo (Português)'].str.extract(r"(Laboratório.*?\;)", expand=False)
df_fapesp['Laboratorio8']  = df_fapesp['Título (Português)'].str.extract(r"(Laboratório.*?\))", expand=False)
df_fapesp['Laboratorio9']  = df_fapesp['Título (Português)'].str.extract(r"(Laboratório.*?\.)", expand=False)
df_fapesp['Laboratorio10'] = df_fapesp['Título (Português)'].str.extract(r"(Laboratório.*?\,)", expand=False)
df_fapesp['Laboratorio11'] = df_fapesp['Título (Português)'].str.extract(r"(Laboratório.*?\-)", expand=False)
df_fapesp['Laboratorio12'] = df_fapesp['Título (Português)'].str.extract(r"(Laboratório.*?\;)", expand=False)
df_fapesp['Laboratorio13'] = df_fapesp['Título (Português)'].str.extract(r"(Laboratório.*?\()", expand=False)
df_fapesp['Laboratorio14'] = df_fapesp['Título (Português)'].str.extract(r"(Laboratório.*?\;)", expand=False)
df_fapesp['Laboratorio15'] = df_fapesp['Assuntos'].str.extract(r"(Laboratório.*?\))", expand=False)
df_fapesp['Laboratorio16'] = df_fapesp['Assuntos'].str.extract(r"(Laboratório.*?\-)", expand=False)


for id in range(0,17):
    df_fapesp['len{0}'.format(id)]  = df_fapesp['Laboratorio{0}'.format(id)].str.len()

In [26]:
df_fapesp['Laboratoriox']   = np.where(  (df_fapesp['len0']<df_fapesp['len1']) & (~df_fapesp['len0'].isnull()) , df_fapesp['Laboratorio0'] ,
                              np.where(  (df_fapesp['len0']<df_fapesp['len2']) & (~df_fapesp['len0'].isnull()) , df_fapesp['Laboratorio0'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len0']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Laboratorio1'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len2']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Laboratorio1'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len3']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Laboratorio1'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len0']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Laboratorio2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len1']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Laboratorio2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len3']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Laboratorio2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len4']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Laboratorio2'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len0']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Laboratorio3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len1']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Laboratorio3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len2']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Laboratorio3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len4']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Laboratorio3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len5']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Laboratorio3'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len0']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Laboratorio4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len1']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Laboratorio4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len2']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Laboratorio4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len5']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Laboratorio4'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len0']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len1']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len2']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len3']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len4']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len0']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Laboratorio6'] , df_fapesp['Laboratorio0'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )

df_fapesp['Laboratorioy']   = np.where(  (df_fapesp['len5']<df_fapesp['len6']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len7']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len8']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len9']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Laboratorio5'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len5']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Laboratorio6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len7']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Laboratorio6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len8']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Laboratorio6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len9']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Laboratorio6'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len5']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Laboratorio7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len6']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Laboratorio7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len8']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Laboratorio7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len9']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Laboratorio7'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len5']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Laboratorio8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len6']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Laboratorio8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len7']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Laboratorio8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len9']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Laboratorio8'] , df_fapesp['Laboratorio9'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )


df_fapesp['Laboratorioz']   = np.where(  (df_fapesp['len10']<df_fapesp['len11']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Laboratorio10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len12']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Laboratorio10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len13']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Laboratorio10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len14']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Laboratorio10'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len10']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Laboratorio10'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len12']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Laboratorio11'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len13']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Laboratorio11'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len14']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Laboratorio11'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len11']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Laboratorio12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len13']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Laboratorio12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len14']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Laboratorio12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len15']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Laboratorio12'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len10']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Laboratorio13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len11']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Laboratorio13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len12']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Laboratorio13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len14']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Laboratorio13'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len10']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Laboratorio14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len11']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Laboratorio14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len12']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Laboratorio14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len13']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Laboratorio14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len15']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Laboratorio14'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len10']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Laboratorio15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len11']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Laboratorio15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len12']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Laboratorio15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len13']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Laboratorio15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len14']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Laboratorio15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len16']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Laboratorio15'] ,
                              np.where(  (df_fapesp['len16']<df_fapesp['len14']) & (~df_fapesp['len16'].isnull()) , df_fapesp['Laboratorio16'] ,
                              np.where(  (df_fapesp['len16']<df_fapesp['len15']) & (~df_fapesp['len16'].isnull()) , df_fapesp['Laboratorio16'] , df_fapesp['Laboratorio0'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )


df_fapesp['Laboratorio']  = np.where( (~df_fapesp['Laboratoriox'].isnull()) , df_fapesp['Laboratoriox'] , 
                            np.where( (~df_fapesp['Laboratorioy'].isnull()) , df_fapesp['Laboratorioy'] , df_fapesp['Laboratorioz']  ) )

In [27]:
df_fapesp['Departamento0']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?\))", expand=False)
df_fapesp['Departamento1']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?\.)", expand=False)
df_fapesp['Departamento2']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?\,)", expand=False)
df_fapesp['Departamento3']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?\-)", expand=False)
df_fapesp['Departamento4']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?\\)", expand=False)
df_fapesp['Departamento5']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?no campus)", expand=False)
df_fapesp['Departamento6']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?Faculdade)", expand=False)
df_fapesp['Departamento7']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?Universidade)", expand=False)
df_fapesp['Departamento8']  = df_fapesp['Resumo (Português)'].str.extract(r"(Departamento.*?\;)", expand=False)
df_fapesp['Departamento9']  = df_fapesp['Título (Português)'].str.extract(r"(Departamento.*?\))", expand=False)
df_fapesp['Departamento10'] = df_fapesp['Título (Português)'].str.extract(r"(Departamento.*?\.)", expand=False)
df_fapesp['Departamento11'] = df_fapesp['Título (Português)'].str.extract(r"(Departamento.*?\,)", expand=False)
df_fapesp['Departamento12'] = df_fapesp['Título (Português)'].str.extract(r"(Departamento.*?\-)", expand=False)
df_fapesp['Departamento13'] = df_fapesp['Título (Português)'].str.extract(r"(Departamento.*?Faculdade)", expand=False)
df_fapesp['Departamento14'] = df_fapesp['Título (Português)'].str.extract(r"(Departamento.*?Universidade)", expand=False)
df_fapesp['Departamento15'] = df_fapesp['Assuntos'].str.extract(r"(Departamento.*?\))", expand=False)
df_fapesp['Departamento16'] = df_fapesp['Assuntos'].str.extract(r"(Departamento.*?\-)", expand=False)


for id in range(0,17):
    print(id)
    df_fapesp['len{0}'.format(id)]  = df_fapesp['Departamento{0}'.format(id)].str.len()


df_fapesp['Departamentox']  = np.where(  (df_fapesp['len0']<df_fapesp['len1']) & (~df_fapesp['len0'].isnull()) , df_fapesp['Departamento0'] ,
                              np.where(  (df_fapesp['len0']<df_fapesp['len2']) & (~df_fapesp['len0'].isnull()) , df_fapesp['Departamento0'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len0']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Departamento1'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len2']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Departamento1'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len3']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Departamento1'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len0']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Departamento2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len1']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Departamento2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len3']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Departamento2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len4']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Departamento2'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len0']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Departamento3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len1']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Departamento3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len2']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Departamento3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len4']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Departamento3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len5']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Departamento3'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len0']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Departamento4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len1']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Departamento4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len2']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Departamento4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len5']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Departamento4'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len0']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len1']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len2']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len3']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len4']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len0']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Departamento6'] , df_fapesp['Departamento0'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )

df_fapesp['Departamentoy']  = np.where(  (df_fapesp['len5']<df_fapesp['len6']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len7']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len8']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len9']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Departamento5'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len5']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Departamento6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len7']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Departamento6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len8']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Departamento6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len9']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Departamento6'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len5']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Departamento7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len6']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Departamento7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len8']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Departamento7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len9']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Departamento7'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len5']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Departamento8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len6']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Departamento8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len7']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Departamento8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len9']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Departamento8'] , df_fapesp['Departamento9'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )


df_fapesp['Departamentoz']  = np.where(  (df_fapesp['len10']<df_fapesp['len11']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Departamento10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len12']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Departamento10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len13']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Departamento10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len14']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Departamento10'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len10']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Departamento10'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len12']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Departamento11'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len13']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Departamento11'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len14']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Departamento11'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len11']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Departamento12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len13']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Departamento12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len14']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Departamento12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len15']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Departamento12'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len10']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Departamento13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len11']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Departamento13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len12']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Departamento13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len14']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Departamento13'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len10']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Departamento14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len11']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Departamento14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len12']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Departamento14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len13']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Departamento14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len15']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Departamento14'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len10']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Departamento15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len11']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Departamento15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len12']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Departamento15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len13']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Departamento15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len14']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Departamento15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len16']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Departamento15'] ,
                              np.where(  (df_fapesp['len16']<df_fapesp['len14']) & (~df_fapesp['len16'].isnull()) , df_fapesp['Departamento16'] ,
                              np.where(  (df_fapesp['len16']<df_fapesp['len15']) & (~df_fapesp['len16'].isnull()) , df_fapesp['Departamento16'] , df_fapesp['Departamento0'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )


df_fapesp['Departamento']  = np.where( (~df_fapesp['Departamentox'].isnull()) , df_fapesp['Departamentox'] , 
                             np.where( (~df_fapesp['Departamentoy'].isnull()) , df_fapesp['Departamentoy'] , df_fapesp['Departamentoz']  ) )

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [ ]:
for id in range(0,17):
    print(id)
    df_fapesp['len{0}'.format(id)]  = df_fapesp['Departamento{0}'.format(id)].str.len()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [28]:
df_fapesp['Universidade0']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?\))", expand=False)
df_fapesp['Universidade1']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?\.)", expand=False)
df_fapesp['Universidade2']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?\,)", expand=False)
df_fapesp['Universidade3']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?\-)", expand=False)
df_fapesp['Universidade4']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?\\)", expand=False)
df_fapesp['Universidade5']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?no campus)", expand=False)
df_fapesp['Universidade6']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?Faculdade)", expand=False)
df_fapesp['Universidade7']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?Universidade)", expand=False)
df_fapesp['Universidade8']  = df_fapesp['Resumo (Português)'].str.extract(r"(Universidade.*?\;)", expand=False)
df_fapesp['Universidade9']  = df_fapesp['Título (Português)'].str.extract(r"(Universidade.*?\))", expand=False)
df_fapesp['Universidade10'] = df_fapesp['Título (Português)'].str.extract(r"(Universidade.*?\.)", expand=False)
df_fapesp['Universidade11'] = df_fapesp['Título (Português)'].str.extract(r"(Universidade.*?\,)", expand=False)
df_fapesp['Universidade12'] = df_fapesp['Título (Português)'].str.extract(r"(Universidade.*?\-)", expand=False)
df_fapesp['Universidade13'] = df_fapesp['Título (Português)'].str.extract(r"(Universidade.*?Faculdade)", expand=False)
df_fapesp['Universidade14'] = df_fapesp['Título (Português)'].str.extract(r"(Universidade.*?Universidade)", expand=False)
df_fapesp['Universidade15'] = df_fapesp['Assuntos'].str.extract(r"(Universidade.*?\))", expand=False)
df_fapesp['Universidade16'] = df_fapesp['Assuntos'].str.extract(r"(Universidade.*?\-)", expand=False)


for id in range(0,17):
    print(id)
    df_fapesp['len{0}'.format(id)]  = df_fapesp['Universidade{0}'.format(id)].str.len()


df_fapesp['Universidadex']  = np.where(  (df_fapesp['len0']<df_fapesp['len1']) & (~df_fapesp['len0'].isnull()) , df_fapesp['Universidade0'] ,
                              np.where(  (df_fapesp['len0']<df_fapesp['len2']) & (~df_fapesp['len0'].isnull()) , df_fapesp['Universidade0'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len0']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Universidade1'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len2']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Universidade1'] ,
                              np.where(  (df_fapesp['len1']<df_fapesp['len3']) & (~df_fapesp['len1'].isnull()) , df_fapesp['Universidade1'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len0']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Universidade2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len1']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Universidade2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len3']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Universidade2'] ,
                              np.where(  (df_fapesp['len2']<df_fapesp['len4']) & (~df_fapesp['len2'].isnull()) , df_fapesp['Universidade2'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len0']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Universidade3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len1']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Universidade3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len2']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Universidade3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len4']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Universidade3'] ,
                              np.where(  (df_fapesp['len3']<df_fapesp['len5']) & (~df_fapesp['len3'].isnull()) , df_fapesp['Universidade3'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len0']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Universidade4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len1']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Universidade4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len2']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Universidade4'] ,
                              np.where(  (df_fapesp['len4']<df_fapesp['len5']) & (~df_fapesp['len4'].isnull()) , df_fapesp['Universidade4'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len0']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len1']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len2']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len3']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len4']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len0']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Universidade6'] , df_fapesp['Universidade0'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )

df_fapesp['Universidadey']  = np.where(  (df_fapesp['len5']<df_fapesp['len6']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len7']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len8']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len5']<df_fapesp['len9']) & (~df_fapesp['len5'].isnull()) , df_fapesp['Universidade5'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len5']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Universidade6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len7']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Universidade6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len8']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Universidade6'] ,
                              np.where(  (df_fapesp['len6']<df_fapesp['len9']) & (~df_fapesp['len6'].isnull()) , df_fapesp['Universidade6'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len5']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Universidade7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len6']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Universidade7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len8']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Universidade7'] ,
                              np.where(  (df_fapesp['len7']<df_fapesp['len9']) & (~df_fapesp['len7'].isnull()) , df_fapesp['Universidade7'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len5']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Universidade8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len6']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Universidade8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len7']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Universidade8'] ,
                              np.where(  (df_fapesp['len8']<df_fapesp['len9']) & (~df_fapesp['len8'].isnull()) , df_fapesp['Universidade8'] , df_fapesp['Universidade9'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )


df_fapesp['Universidadez']  = np.where(  (df_fapesp['len10']<df_fapesp['len11']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Universidade10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len12']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Universidade10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len13']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Universidade10'] ,
                              np.where(  (df_fapesp['len10']<df_fapesp['len14']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Universidade10'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len10']) & (~df_fapesp['len10'].isnull()) , df_fapesp['Universidade10'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len12']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Universidade11'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len13']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Universidade11'] ,
                              np.where(  (df_fapesp['len11']<df_fapesp['len14']) & (~df_fapesp['len11'].isnull()) , df_fapesp['Universidade11'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len11']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Universidade12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len13']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Universidade12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len14']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Universidade12'] ,
                              np.where(  (df_fapesp['len12']<df_fapesp['len15']) & (~df_fapesp['len12'].isnull()) , df_fapesp['Universidade12'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len10']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Universidade13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len11']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Universidade13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len12']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Universidade13'] ,
                              np.where(  (df_fapesp['len13']<df_fapesp['len14']) & (~df_fapesp['len13'].isnull()) , df_fapesp['Universidade13'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len10']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Universidade14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len11']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Universidade14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len12']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Universidade14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len13']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Universidade14'] ,
                              np.where(  (df_fapesp['len14']<df_fapesp['len15']) & (~df_fapesp['len14'].isnull()) , df_fapesp['Universidade14'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len10']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Universidade15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len11']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Universidade15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len12']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Universidade15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len13']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Universidade15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len14']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Universidade15'] ,
                              np.where(  (df_fapesp['len15']<df_fapesp['len16']) & (~df_fapesp['len15'].isnull()) , df_fapesp['Universidade15'] ,
                              np.where(  (df_fapesp['len16']<df_fapesp['len14']) & (~df_fapesp['len16'].isnull()) , df_fapesp['Universidade16'] ,
                              np.where(  (df_fapesp['len16']<df_fapesp['len15']) & (~df_fapesp['len16'].isnull()) , df_fapesp['Universidade16'] , df_fapesp['Universidade0'] ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )


df_fapesp['Universidade']  = np.where( (~df_fapesp['Universidadex'].isnull()) , df_fapesp['Universidadex'] , 
                            np.where( (~df_fapesp['Universidadey'].isnull()) , df_fapesp['Universidadey'] , df_fapesp['Universidadez']  ) )

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

In [29]:
colunas = ['N. Processo','Departamento','Laboratorio','Universidade']

df_fapesp[colunas][df_fapesp['LAB_RESUMO']==1].head()

,N. Processo,Departamento,Laboratorio,Universidade
3,24/09315-9,Departamento de Design e ao Programa de Pós-gr...,Laboratório de Ergonomia e Interfaces (LEI),Universidade Estadual Paulista (Unesp)
8,24/04810-1,NaN,NaN,NaN
11,24/05860-2,NaN,Laboratório de Captura de Carbono (LC3),NaN
12,24/06101-8,NaN,Laboratório de Combustão e Captura de Carbono ...,NaN
20,24/02733-0,NaN,Laboratório de Diversidade Genética e Evolução...,"Universidade de Columbia, EUA)"

In [30]:
df_fapesp.shape

(292876, 121)

In [ ]:
df_fapesp[colunas][df_fapesp['LAB_RESUMO']==1].to_excel('LAB_RESUMO.xlsx')

In [31]:
df_fapesp.drop(columns = ['Departamento0','Departamento1','Departamento2','Departamento3','Departamento4','Departamento5','Departamento6','Departamento7','Departamento8','Departamento9','Departamento10','Departamento11','Departamento12','Departamento13','Departamento14','Departamento15','Departamento16'] ,axis=1,inplace=True)

df_fapesp.drop(columns = ['Laboratorio0','Laboratorio1','Laboratorio2','Laboratorio3','Laboratorio4','Laboratorio5','Laboratorio6','Laboratorio7','Laboratorio8','Laboratorio9','Laboratorio10','Laboratorio11','Laboratorio12','Laboratorio13','Laboratorio14','Laboratorio15','Laboratorio16'] ,axis=1,inplace=True)

df_fapesp.drop(columns = ['Laboratoriox','Laboratorioy','Laboratorioz','Departamentox','Departamentoy','Departamentoz'] ,axis=1,inplace=True)

In [32]:
df_fapesp.drop(columns = ['len0','len1','len2','len3','len4','len5','len6','len7','len8','len9','len10','len11','len12','len13','len14','len15','len16'] ,axis=1,inplace=True)

In [33]:
df_fapesp0 = df_fapesp[  ( df_fapesp['LAB_RESUMO']==1) ].copy()
df_fapesp1 = df_fapesp0[ (~df_fapesp['Laboratorio'].isnull())].copy()
df_fapesp2 = df_fapesp1[ (~df_fapesp['Departamento'].isnull())].copy()
df_fapesp2.to_excel('fapesp_labs.xlsx')
df_fapesp2.shape

C:\Users\patrick.franco\AppData\Local\Temp\ipykernel_6712\224348413.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_fapesp1 = df_fapesp0[ (~df_fapesp['Laboratorio'].isnull())].copy()
C:\Users\patrick.franco\AppData\Local\Temp\ipykernel_6712\224348413.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_fapesp2 = df_fapesp1[ (~df_fapesp['Departamento'].isnull())].copy()

(964, 64)

In [34]:
df_fapesp[ (df_fapesp['LAB_RESUMO']==1) & (~df_fapesp['Laboratorio'].isnull())].shape

(6099, 64)

In [ ]:
import pandas as pd

df = pd.DataFrame([
    ['Desde 2002, o Laboratório de Ergonomia e Interfaces (LEI) da Universidade Estadual Paulista (Unesp), campus Bauru-SP, associado ao Departamento de Design e ao Programa de Pós-graduação em Design, tem reunido pesquisadores, docentes, pós-doutorandos, doutorandos, mestrandos, graduandos e estudantes de iniciação científica em torno de pesquisas e estudos no campo do Design Ergonômico, com o objetivo de entender a inter-relação e o equilíbrio entre Design e Ergonomia, com especial foco na usabilidade. A presente proposta visa dar continuidade às atividades de pesquisa, formação acadêmica e desenvolvimento científico, proporcionando um incremento substancial na qualidade dessas atividades' ],
], columns = ['resumo'])

df['Laboratorio'] = df['resumo'].str.extract(r"(Laboratório.*\))", expand=False)

In [ ]:
df.head().transpose()

                                                             0
resumo       Desde 2002, o Laboratório de Ergonomia e Inter...
Laboratorio  Laboratório de Ergonomia e Interfaces (LEI) da...

In [ ]:
# Estudar esse site
# https://huyenchip.com/2024/07/25/genai-platform.html

In [ ]:
# https://pystoned.readthedocs.io/en/latest/examples/DEA/dea_ddf.html
# https://pystoned.readthedocs.io/en/latest/examples/StoNED/mom.html