In [14]:
import os
import sys
import pandas as pd
import pickle
import string  
import numpy as np

In [15]:
#Importando o conjunto de dados
df_areas = pd.read_excel('labs_mcti2.xlsx' , sheet_name='areas_labs')

In [16]:
df_areas.head()

,site_mcti,lab,areas
0,https://pnipe.mcti.gov.br/laboratory/10006,10006,Genômica
1,https://pnipe.mcti.gov.br/laboratory/10006,10006,Proteômica
2,https://pnipe.mcti.gov.br/laboratory/10006,10006,Epigenômica
3,https://pnipe.mcti.gov.br/laboratory/10006,10006,sequenciador Miseq (Illumina)
4,https://pnipe.mcti.gov.br/laboratory/10006,10006,Luminex

In [17]:
df_areas.dtypes

site_mcti    object
lab           int64
areas        object
dtype: object

In [18]:
#https://zenodo.org/records/11185049

In [19]:
df_areas.groupby('areas').count()

                                                    site_mcti  lab
areas
 Análise térmica por TGA                                    5    5
 Desenvolvimento de formulação                              4    4
 Destilação Atmosférica (Baseado na ASTM D2892)             1    1
 Detecção de processos de relaxação moleculares             1    1
 Espectrofotômetro UV-VIS                                   7    7
...                                                       ...  ...
●\tTestes in vivo - cicatrização, gastroproteçã...          1    1
\tCaracterização de Sedimentos finos                       1    1
\tHidrodinâmica de estuários                               2    2
\tInfraestruturas marítimas de acesso portuári...          1    1
\tPropagação de maré em águas rasas                        1    1

[24825 rows x 2 columns]

In [ ]:
import string  
import pandas as pd
import numpy as np


df_areas['Petro'] = np.where( df_areas['areas'].str.contains("Exploração Offshore", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Exploração Onshore", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Sísmica", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração Exploratória", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Blocos Exploratórios", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Margem Equatorial", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Bacias Sedimentares", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Destilação Atmosférica:", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Destilação a Vácuo", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Craqueamento Catalítico", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Hidrotratamento", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Reforma Catalítica:", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Alquilação", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Isomerização", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Desasfaltação", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Petróleo", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("petroquímica", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Gás natural", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Petróleo", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Petrobras", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Gasolina", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração Rotativa", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração Direcional", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração Horizontal", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração Offshore", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração Onshore", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração de Desenvolvimento", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Perfuração Onshore", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Reservatórios de Óleo", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Reservatórios de Gás", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Rochas-Reservatório", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Armadilhas de Petróleo", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Injeção de Água", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Recuperação Aprimorada", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Gasolina", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Pré-Sal", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Bacia de Campos", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Bacia de Santos", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Engenharia Submarina", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Diesel", case=False, na=False), 1 ,
                    np.where( df_areas['areas'].str.contains("Desenvolvimento de Reservatórios", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Segurança energetica", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("hidrocarbonetos", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Querosene", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Metano", case=False, na=False), 1 ,  
                    np.where( df_areas['areas'].str.contains("Segurança energetica", case=False, na=False), 1 ,                                                                              
                    np.where( df_areas['areas'].str.contains("Perfuração de Avaliação", case=False, na=False), 1 , 0 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )   



#Reservatórios de Óleo: Estruturas geológicas que armazenam hidrocarbonetos no estado líquido1.
#Reservatórios de Gás: Estruturas geológicas que armazenam hidrocarbonetos no estado gasoso1.
#Rochas-Reservatório: Rochas porosas e permeáveis que permitem o armazenamento de petróleo em volumes significativos2.
#Armadilhas de Petróleo: Estruturas geológicas que impedem a migração do petróleo, como anticlinais, falhas geológicas e domos salinos2.
#Injeção de Água: Técnica utilizada para manter a pressão e a mobilidade do petróleo dentro dos reservatórios3.
#Recuperação Aprimorada (EOR): Métodos para aumentar a eficiência da extração de petróleo dos reservatórios3.
#Perfuração Rotativa: Técnica que utiliza uma broca giratória para romper as rochas1.
#Perfuração Direcional: Técnica que permite desviar o furo de sua trajetória vertical para acessar múltiplos reservatórios a partir de um único ponto2.
#Perfuração Horizontal: Técnica que estende os poços lateralmente através dos reservatórios, aumentando a eficiência da extração1.
#Perfuração Offshore: Perfuração realizada em plataformas marítimas para acessar reservas submarinas2.
#Perfuração Onshore: Perfuração realizada em terra firme para acessar reservas subterrâneas2.
#Perfuração de Desenvolvimento: Perfuração de poços adicionais em um campo já descoberto para otimizar a produção2.
#Perfuração de Avaliação: Perfuração de poços para avaliar a extensão e a qualidade de uma descoberta de petróleo ou gás2.
#Exploração Offshore: Busca por reservas de petróleo e gás em áreas marítimas.
#Exploração Onshore: Busca por reservas de petróleo e gás em áreas terrestres.
#Sísmica: Técnica de levantamento geofísico para mapear estruturas subterrâneas.
#Perfuração Exploratória: Perfuração de poços para descobrir novas reservas.
#Blocos Exploratórios: Áreas designadas para exploração de petróleo e gás.
#Margem Equatorial: Nova fronteira exploratória no Brasil, especialmente no norte do país1.
#Bacias Sedimentares: Regiões geológicas onde se acumulam sedimentos que podem conter petróleo e gás.
#Destilação Atmosférica: Processo inicial de separação dos componentes do petróleo bruto.
#Destilação a Vácuo: Técnica para refinar frações mais pesadas do petróleo.
#Craqueamento Catalítico: Processo que quebra moléculas maiores em menores, produzindo gasolina e outros produtos leves.
#Hidrotratamento: Remoção de impurezas como enxofre e nitrogênio dos produtos refinados.
#Reforma Catalítica: Processo que aumenta o número de octanas na gasolina.
#Alquilação: Produção de componentes de alta octanagem para gasolina.
#Coking: Conversão de resíduos pesados em produtos mais leves e coque de petróleo.
#Isomerização: Conversão de hidrocarbonetos para melhorar a qualidade da gasolina.
#Desasfaltação: Separação de asfaltenos do petróleo para melhorar a qualidade dos produtos refinados.

In [27]:
df_areas.groupby(['Petro']).count()

       site_mcti    lab  areas
Petro
0          64334  64334  64292
1            250    250    250

In [32]:
len(df_areas['lab'][df_areas['Petro']==1].unique())

174

## Unificando Dados da FAPESP

In [9]:
#Importando o conjunto de dados
df_nomes = pd.read_excel('labs_mcti2.xlsx' , sheet_name='cadatro_nomes')

In [10]:
df_nomes.shape

(6323, 13)

In [11]:
df_nomes.head()

,lab,site_mcti,nome_lab,data_de_criacao,universidade,nome_responsavel,tel,endereco,cidade,cep,email,site_lab,sobre
0,10006,https://pnipe.mcti.gov.br/laboratory/10006,CTO - Centro de Tecnologias Ômicas,17/03/2022,USP - Universidade de São Paulo,Mario Hiroyuki Hirata,(55) 11998-3877,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,NaN,NaN,Utilizado para o desenvolvimento de pesquisas ...
1,10008,https://pnipe.mcti.gov.br/laboratory/10008,NB3 - Laboratório Multiusuário com Nivel de Bi...,17/03/2022,USP - Universidade de São Paulo,Mario Hiroyuki Hirata,(55) 11998-3877,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,mhhirata@usp.br,https://uspmulti.prp.usp.br/public/centrais/126,O laboratório de biossegurança Nível 3 do Depa...
2,10037,https://pnipe.mcti.gov.br/laboratory/10037,IA BMF - ICB/USP - Instalação Animal do Depart...,18/03/2022,USP - Universidade de São Paulo,Eliana Akamine,(11) 3091-7317,Professor Lineu Prestes,São Paulo - SP - 1524,Veja como chegar,biot.farmaco@icb.usp.br,NaN,Trata-se de biotério utilizado pelos pesquisad...
3,1004,https://pnipe.mcti.gov.br/laboratory/1004,Mietto Lab - Lab. de Biologia Celular,22/09/2020,UFJF - Universidade Federal de Juiz de Fora,Bruno Siqueira Mietto,(21) 99934-0074,Rua José Lourenço Kelmer,Juiz de Fora - MG - s/n,Veja como chegar,bruno.mietto@ufjf.edu.br,NaN,Laboratório de pesquisa em neurobiologia com ê...
4,10057,https://pnipe.mcti.gov.br/laboratory/10057,QA/SECTEC/LAPOC - Laboratório de Radiometria e...,21/03/2022,CNEN - Comissão Nacional de Energia Nuclear,Rodrigo Leandro Bonifácio,(35) 3716-7029,Poços de Caldas - Andradas,Poços de Caldas - MG - km13,Veja como chegar,lapoc@cnen.gov.br,http://www.cnenpc.gov.br,Os laboratórios de Química Analítica e Radiome...

In [ ]:
len(df_areas['lab'][df_areas['Petro']==1].unique())

In [34]:
df_nomes[df_nomes['lab'].isin(df_areas['lab'][df_areas['Petro']==1].unique())].head()

,lab,site_mcti,nome_lab,data_de_criacao,universidade,nome_responsavel,tel,endereco,cidade,cep,email,site_lab,sobre
11,10117,https://pnipe.mcti.gov.br/laboratory/10117,LATAB - Laboratório de Tabaco e Derivados,28/03/2022,INT - Instituto Nacional de Tecnologia,SIMONE CHIAPETTA,(21) 2123-1090,Av. Venezuela,Rio de Janeiro - RJ - 82,Veja como chegar,NaN,NaN,Laboratório que atua na prestação de serviços ...
260,1148,https://pnipe.mcti.gov.br/laboratory/1148,LABRMN-L - Laboratório Multiusuário de Ressonâ...,24/09/2020,UFRJ - Universidade Federal do Rio de Janeiro,Carlos Kaiser,(21) 98762-6970,Avenida Athos da Silveira Ramos 149,Rio de Janeiro - RJ - 148,Veja como chegar,labrmn@iq.ufrj.br,https://labrmn.iq.ufrj.br/,Laboratório de análises instrumentais por RMN ...
309,11647,https://pnipe.mcti.gov.br/laboratory/11647,LAPROMAQ - Laboratório de Proteínas e Microrga...,12/08/2022,UFRGS - Universidade Federal do Rio Grande do Sul,ROBERTA RODRIGUES,(51) 98111-5376,Bento Gonçalves,Porto Alegre - RS - 9500,Veja como chegar,roberta.bussamara@ufrgs.br,NaN,O Laboratório atua no desenvolvimento de pesqu...
363,11836,https://pnipe.mcti.gov.br/laboratory/11836,PROCAT - Laboratório de Processos Catalíticos,23/08/2022,UFRGS - Universidade Federal do Rio Grande do Sul,Oscar Perez Lopez,(51) 3308-5708,Ramiro Barcelos,Porto Alegre - RS - 2777,Veja como chegar,perez@ufrgs.br,https://www.ufrgs.br/dequi-labs/procat/,No Laboratório de Processos Catalíticos são re...
364,11842,https://pnipe.mcti.gov.br/laboratory/11842,LABMATER - Laboratório de Materiais e Energias...,23/08/2022,UFPR - Universidade Federal do Paraná,Helton José Alves,(45) 99912-2880,Rua Pioneiro,Palotina - PR - 2153,Veja como chegar,labmater@ufpr.br,https://palotina.ufpr.br/labmater/,O Laboratório de Materiais e Energias Renováve...

In [ ]:
df_nomes['Petro'] = np.where( df_nomes['sobre'].str.contains("Exploração Offshore", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Exploração Onshore", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Sísmica", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração Exploratória", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Blocos Exploratórios", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Margem Equatorial", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Bacias Sedimentares", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Destilação Atmosférica:", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Destilação a Vácuo", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Craqueamento Catalítico", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Hidrotratamento", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Reforma Catalítica:", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Alquilação", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Isomerização", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Desasfaltação", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Petróleo", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("petroquímica", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Gás natural", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Petróleo", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Petrobras", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Gasolina", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração Rotativa", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração Direcional", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração Horizontal", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração Offshore", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração Onshore", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração de Desenvolvimento", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Perfuração Onshore", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Reservatórios de Óleo", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Reservatórios de Gás", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Rochas-Reservatório", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Armadilhas de Petróleo", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Injeção de Água", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Recuperação Aprimorada", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Gasolina", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Pré-Sal", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Bacia de Campos", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Bacia de Santos", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Engenharia Submarina", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Diesel", case=False, na=False), 1 ,
                    np.where( df_nomes['sobre'].str.contains("Desenvolvimento de Reservatórios", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Segurança energetica", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("hidrocarbonetos", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Querosene", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Metano", case=False, na=False), 1 ,  
                    np.where( df_nomes['sobre'].str.contains("Segurança energetica", case=False, na=False), 1 ,                                                                              
                    np.where( df_nomes['sobre'].str.contains("Perfuração de Avaliação", case=False, na=False), 1 , 0 ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) ) )

In [ ]:
# Estudar esse site
# https://huyenchip.com/2024/07/25/genai-platform.html

In [37]:
df_nomes_petro = df_nomes[ (df_nomes['lab'].isin(df_areas['lab'][df_areas['Petro']==1].unique())) |
                           (df_nomes['Petro']==1 )].copy()

In [38]:
df_nomes_petro.shape

(250, 14)

In [40]:
df_areas_petro = df_areas[ (df_areas['lab'].isin(df_nomes['lab'][df_nomes['Petro']==1].unique())) |
                           (df_areas['Petro']==1 )].copy()

In [41]:
df_areas_petro.shape

(1786, 4)

In [45]:
#Importando o conjunto de dados
df_equip = pd.read_excel('labs_mcti2.xlsx' , sheet_name='codigos_equip')

In [47]:
df_equip.dtypes

site_mcti    object
lab           int64
codigos      object
dtype: object

In [48]:
#codigos_equip
df_equip_petro = df_equip[ (df_equip['lab'].isin(df_nomes['lab'][df_nomes['Petro']==1].unique())) |
                           (df_equip['lab'].isin(df_areas['lab'][df_areas['Petro']==1].unique())) ].copy()

In [49]:
df_equip_petro.shape

(1268, 3)

In [51]:
df_nomes_petro.to_excel('labs_mcti_petro1.xlsx',sheet_name='cadatro_nomes')
df_areas_petro.to_excel('labs_mcti_petro2.xlsx',sheet_name='areas_labs')
df_equip_petro.to_excel('labs_mcti_petro3.xlsx',sheet_name='codigos_equip')

In [ ]:
# https://pystoned.readthedocs.io/en/latest/examples/DEA/dea_ddf.html
# https://pystoned.readthedocs.io/en/latest/examples/StoNED/mom.html